# Generated by Django 6.0.6 on 2026-06-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unibooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Matricule'),
        ),
    ]
