# Generated by Django 6.0.6 on 2026-06-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unibooks', '0002_utilisateur_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandelivre',
            name='auteur',
            field=models.CharField(blank=True, max_length=255, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='demandelivre',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='demandelivre',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=12, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de couverture'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=True, verbose_name='Doit changer son mot de passe'),
        ),
    ]
