# Generated by Django 6.0.6 on 2026-06-27 06:32

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unibooks', '0003_alter_demandelivre_auteur_alter_demandelivre_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unibooks.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EtudiantProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('unibooks.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
