# Generated by Django 6.0.6 on 2026-07-09 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unibooks', '0004_adminproxy_etudiantproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivreLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_like', models.DateTimeField(auto_now_add=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='unibooks.livre', verbose_name='Livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livre_likes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "J'aime (Livre)",
                'unique_together': {('livre', 'utilisateur')},
            },
        ),
    ]
