# Generated by Django 6.0.6 on 2026-07-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unibooks', '0007_alter_notification_destinataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='fichier',
            field=models.FileField(blank=True, help_text="PDF ou autre format. Laissez vide si le livre n'est pas téléchargeable.", null=True, upload_to='livres/fichiers/', verbose_name='Fichier téléchargeable'),
        ),
    ]
